// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported by this app.');
      default:
        throw UnsupportedError('Unknown platform: $defaultTargetPlatform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyXeKyUpsgLYwi8xwKrF2lp3pnIWaegM0',
    appId: '1:603318309456:web:935e43e49b44f2c591b755',
    messagingSenderId: '603318309456',
    projectId: 'example-ccae8',
    authDomain: 'example-ccae8.firebaseapp.com',
    storageBucket: 'example-ccae8.firebasestorage.app',
  );

  // ─── Web ───────────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_4ow6yn9VXiSL3Vunw6Gl1vzQYjFdwU',
    appId: '1:603318309456:android:a17e2a936958c97b91b755',
    messagingSenderId: '603318309456',
    projectId: 'example-ccae8',
    storageBucket: 'example-ccae8.firebasestorage.app',
  );

  // ─── Android ────────────────────────────────────────────────────────────────

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOeSHwXmiLlvMX4wiMJsKSucusa3flOcQ',
    appId: '1:603318309456:ios:a89d4b3f02e52b2f91b755',
    messagingSenderId: '603318309456',
    projectId: 'example-ccae8',
    storageBucket: 'example-ccae8.firebasestorage.app',
    iosBundleId: 'com.example.smartFileApp',
  );

  // ─── iOS ───────────────────────────────────────────────────────────────────

  // ─── macOS ─────────────────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyExample_replace_with_real_key',
    appId: '1:000000000000:ios:example_replace',
    messagingSenderId: '000000000000',
    projectId: 'example-ccae8',
    storageBucket: 'example-ccae8.firebasestorage.app',
    iosBundleId: 'com.example.smartFileApp',
  );

  // ─── Windows ───────────────────────────────────────────────────────────────
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyExample_replace_with_real_key',
    appId: '1:000000000000:web:example_replace',
    messagingSenderId: '000000000000',
    projectId: 'example-ccae8',
    authDomain: 'example-ccae8.firebaseapp.com',
    storageBucket: 'example-ccae8.firebasestorage.app',
  );
}